- hosts: localhost
  become: true

  roles:
  - role: create-volumes
    volumes_path: /var/lib/docker/openshift-volumes
    namespaces:
      - name: vault
        volumes:
          - name: vault-file
            capacity: 5Gi
          - name: vault-logs
            capacity: 5Gi
      - name: gitlab
        volumes:
          - name: etc-gitlab
            capacity: 1Gi
          - name: gitlab-data
            capacity: 20Gi
            owner: 998
            group: 998
            mode: '0750'
          - name: var-lib-pgsql-data
            capacity: 5Gi
          - name: redis-data
            capacity: 2Gi
      - name: nextcloud
        volumes:
          - name: appdata
            capacity: 100Gi
          - name: var-www-html
            capacity: 1Gi
          - name: var-lib-mysql-data
            capacity: 5Gi
          - name: redis-data
            capacity: 2Gi
      - name: redmine
        volumes:
          - name: usr-src-redmine-files
            capacity: 20Gi
          - name: var-lib-mysql-data
            capacity: 10Gi
      - name: sogo
        volumes:
          - name: var-lib-mysql-data
            capacity: 10Gi
          - name: backups
            capacity: 20Gi
          - name: etc-sogo
            capacity: 1Gi
          - name: var-log-sogo
            capacity: 5Gi
      - name: xwiki
        volumes:
          - name: var-lib-mysql-data
            capacity: 20Gi
          - name: xwiki-data
            capacity: 20Gi
